---
- name: Source profile
  shell: source /etc/profile

- name: Setenforce
  shell: setenforce 0 || true

- name: Restart sshd
  service: name=sshd state=restarted

- name: Exec network config
  shell: sh /tmp/network.sh

- name: Restart chronyd
  service: name=chronyd state=restarted

- name: Restart ntpd
  service: name=ntpd state=restarted

- name: Restart rsyslog service
  service: name=rsyslog state=restarted enabled=yes
