---
- name: Pass length and count limit
  lineinfile: dest={{ item.dest }} regexp={{ item.regexp }} insertafter={{ item.insertafter }} line={{ item.line }}
  with_items:
    - { dest: '/etc/login.defs',regexp: '^PASS_MIN_LEN',insertafter: '^PASS_MIN_DAYS',line: 'PASS_MIN_LEN    8' }
    - { dest: '/etc/pam.d/system-auth',regexp: '/lib64/security/pam_tally2.so',insertafter: 'pam_env.so',line: 'auth        required      /lib64/security/pam_tally2.so deny=3 unlock_time=300' }
  tags: pass_and_count_limit

- name: Disable and stop system service
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - 'NetworkManager'
    - 'firewalld'
    - 'postfix'
  tags: stop_system_service

- name: Hostname config
  hostname: name={{ ansible_default_ipv4.address.replace('.','e') }}
  tags: hostname_config

- name: Sshd and ssh config
  shell: sed 's/#Port 22/Port 22/g' /etc/ssh/sshd_config -i;sed 's/^#Protocol 2/Protocol 2/g' /etc/ssh/sshd_config -i;sed 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config -i;sed 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config -i;sed 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/ssh_config -i
  notify: Restart sshd
  tags: sshd_config
