---
- name: Install ntpd
  yum: name=ntp state=present
  tags: install_ntp

- name: Copy the ntpd configuration file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntpd
  tags: install_ntp

- name: Be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
  tags: install_ntp
