---
- name: Make haproxy bindable on non local addresses
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present

- name: Make net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present

- name: Add group haproxy
  group: name=haproxy state=present

- name: Add user haproxy
  user: name=haproxy group=haproxy home=/home/haproxy state=present

- name: Install haproxy keepalived rpm package
  yum: name={{ item }} state=present
  with_items:
    - keepalived
    - haproxy

- name: Copy haproxy keepalived conf file
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: "haproxy.cfg.j2", dest: "/etc/haproxy/haproxy.cfg", mode: "0644" }
    - { src: "keepalived.conf.j2", dest: "/etc/keepalived/keepalived.conf", mode: "0644" }
    - { src: "check_haproxy.sh.j2",dest: "/etc/keepalived/check_haproxy.sh", mode: "0755" }
  notify: Restart keepalived
