---
- name: Set rabbitmq limitnofile
  lineinfile:
    path: /usr/lib/systemd/system/rabbitmq-server.service
    insertafter: 'Group=rabbitmq'
    line: 'LimitNOFILE=10240'

- name: Config rabbitmq
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq-server

- name: Be sure rabbitmq is running and enabled
  service: name=rabbitmq-server state=started enabled=yes
